name: Run tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install dependencies
        run: |
          pip install codecov
          python scripts/ci/install
      - name: Install Thundra Python Agent
        uses: thundra-io/thundra-foresight-python-action@python-action
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
          agent_version: 3.0.0
      - name: Run tests
        run: |
          python scripts/ci/run-tests --with-cov --with-xdist
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.me/v1
          THUNDRA_AGENT_DEBUG_ENABLE: true
      - name: Run codecov
        run: |
          rm tests/coverage.xml
          mv tests/.coverage ./
          codecov
